# Generated by Django 4.2.7 on 2023-12-07 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_acompanhamento_cadastro_enderecodoscadastros_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integracao',
            name='cadastro',
        ),
        migrations.DeleteModel(
            name='Acompanhamento',
        ),
    ]
